---
name: go-test

on:
  pull_request:
    branches:
      - '*'

jobs:
  go-test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go environment
        uses: red-hat-storage/managed-fusion-agent@main
      - name: Run go test
        run: make test
